- name: Install zsh
  apt: name=zsh
  tags:
    - zsh

- name: Change shell
  shell: chsh -s `which zsh`
  tags:
    - zsh

- name: oh my zsh installation
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  tags:
    - zsh

- name: add auto suggestion plugin
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: '~/.oh-my-zsh/plugins/zsh-autosuggestions'
  tags:
    - zsh

- name: update our zshrc
  shell: sed -i 's/(git/(git zsh-autosuggestions' ~/.zshrc
  tags:
    - zsh

