- hosts: localhost
  become: true
  pre_taks:
    - name: Update cache
      apt:
        update_cache: true
      tags:
        - zsh
        - node
  tasks:
    - include: tasks/zsh.yml
    - include: tasks/node.yml
